export default function handler(req, res) {
  const events = [
    {
      id: "1",
      title: "Boston Marathon 2025",
      type: "Marathon",
      date: "2025-04-21",
      location: "Boston, MA",
      distance: "26.2 miles",
      tags: ["Marathon", "Road", "Qualifier", "World Major"],
      source: "baa",
      url: "https://www.baa.org",
    },
    {
      id: "2",
      title: "Ironman Lake Placid",
      type: "Triathlon",
      date: "2025-07-27",
      location: "Lake Placid, NY",
      distance: "140.6 miles",
      tags: ["Triathlon", "Ironman", "Full Distance"],
      source: "ironman",
      url: "https://www.ironman.com",
    },
    {
      id: "3",
      title: "New York City Marathon",
      type: "Marathon",
      date: "2025-11-02",
      location: "New York, NY",
      distance: "26.2 miles",
      tags: ["Marathon", "Road", "World Major"],
      source: "nyrr",
      url: "https://www.tcsnycmarathon.org",
    },
    {
      id: "4",
      title: "Chicago Marathon",
      type: "Marathon",
      date: "2025-10-12",
      location: "Chicago, IL",
      distance: "26.2 miles",
      tags: ["Marathon", "Road", "World Major", "Fast Course"],
      source: "chicagomarathon",
      url: "https://www.chicagomarathon.com",
    },
    {
      id: "5",
      title: "Ironman 70.3 World Championship",
      type: "Triathlon",
      date: "2025-09-07",
      location: "Taupo, New Zealand",
      distance: "70.3 miles",
      tags: ["Triathlon", "Half Distance", "Championship"],
      source: "ironman",
      url: "https://www.ironman.com",
    },
    {
      id: "6",
      title: "Leadville Trail 100",
      type: "Ultra",
      date: "2025-08-16",
      location: "Leadville, CO",
      distance: "100 miles",
      tags: ["Ultra", "Trail", "Mountain"],
      source: "leadville",
      url: "https://www.leadvilleraceseries.com",
    },
    {
      id: "7",
      title: "Tour de France Gran Fondo",
      type: "Cycling",
      date: "2025-07-05",
      location: "France",
      distance: "100 km",
      tags: ["Cycling", "Gran Fondo", "Road"],
      source: "letour",
      url: "https://www.letour.fr",
    },
    {
      id: "8",
      title: "Spartan Race World Championship",
      type: "Obstacle Race",
      date: "2025-11-15",
      location: "Sparta, Greece",
      distance: "13+ miles",
      tags: ["Obstacle Race", "Championship", "Elite"],
      source: "spartan",
      url: "https://www.spartan.com",
    },
    {
      id: "9",
      title: "Berlin Marathon",
      type: "Marathon",
      date: "2025-09-28",
      location: "Berlin, Germany",
      distance: "26.2 miles",
      tags: ["Marathon", "Road", "World Major", "Fast Course"],
      source: "bmw-berlin-marathon",
      url: "https://www.bmw-berlin-marathon.com",
    },
    {
      id: "10",
      title: "Kona Ironman World Championship",
      type: "Triathlon",
      date: "2025-10-11",
      location: "Kona, HI",
      distance: "140.6 miles",
      tags: ["Triathlon", "Ironman", "World Championship"],
      source: "ironman",
      url: "https://www.ironman.com",
    },
    {
      id: "11",
      title: "Western States 100",
      type: "Ultra",
      date: "2025-06-28",
      location: "Olympic Valley, CA",
      distance: "100 miles",
      tags: ["Ultra", "Trail", "Mountain"],
      source: "wser",
      url: "https://www.wser.org",
    },
    {
      id: "12",
      title: "Tokyo Marathon",
      type: "Marathon",
      date: "2025-03-02",
      location: "Tokyo, Japan",
      distance: "26.2 miles",
      tags: ["Marathon", "Road", "World Major"],
      source: "marathon.tokyo",
      url: "https://www.marathon.tokyo",
    },
    {
      id: "13",
      title: "Santa Monica 5K",
      type: "5K",
      date: "2025-05-10",
      location: "Santa Monica, CA",
      distance: "3.1 miles",
      tags: ["5K", "Road", "Beach"],
      source: "local",
      url: "#",
    },
    {
      id: "14",
      title: "Boulder Peak Triathlon",
      type: "Triathlon",
      date: "2025-06-15",
      location: "Boulder, CO",
      distance: "Olympic",
      tags: ["Triathlon", "Olympic Distance", "Mountain"],
      source: "boulderpeaktri",
      url: "#",
    },
    {
      id: "15",
      title: "Seattle Half Marathon",
      type: "Half Marathon",
      date: "2025-11-30",
      location: "Seattle, WA",
      distance: "13.1 miles",
      tags: ["Half Marathon", "Road", "Pacific Northwest"],
      source: "seattlemarathon",
      url: "#",
    },
    {
      id: "16",
      title: "Austin Trail Run 10K",
      type: "Trail Run",
      date: "2025-04-05",
      location: "Austin, TX",
      distance: "10K",
      tags: ["Trail", "10K", "Hills"],
      source: "texastrailruns",
      url: "#",
    },
    {
      id: "17",
      title: "Miami Beach Sprint Triathlon",
      type: "Triathlon",
      date: "2025-05-25",
      location: "Miami Beach, FL",
      distance: "Sprint",
      tags: ["Triathlon", "Sprint Distance", "Beach"],
      source: "miamibeachtri",
      url: "#",
    },
    {
      id: "18",
      title: "Portland Century Ride",
      type: "Cycling",
      date: "2025-08-03",
      location: "Portland, OR",
      distance: "100 miles",
      tags: ["Cycling", "Century", "Road"],
      source: "portlandcycling",
      url: "#",
    },
    {
      id: "19",
      title: "San Francisco Marathon",
      type: "Marathon",
      date: "2025-07-27",
      location: "San Francisco, CA",
      distance: "26.2 miles",
      tags: ["Marathon", "Road", "Hills"],
      source: "thesfmarathon",
      url: "#",
    },
    {
      id: "20",
      title: "Nashville Rock 'n' Roll Half",
      type: "Half Marathon",
      date: "2025-04-26",
      location: "Nashville, TN",
      distance: "13.1 miles",
      tags: ["Half Marathon", "Road", "Music"],
      source: "runrocknroll",
      url: "#",
    },
  ];

  res.status(200).json(events);
}
